const express = require("express")
const Joi = require("joi")
const cors = require("cors")
const list = require("./routes/track")
const app = express()
app.use(express.json())
app.use(cors())
app.use("/list", list)

app.listen(5000, () =>{console.log("Listning on port 5000")})