const express = require("express")
const Joi = require("joi")
const cors = require("cors")
const history = require("./routes/track")
const fee = require("./routes/watchPayment")
const app = express()
app.use(express.json())
app.use(cors())
app.use("/list", history)
app.use("/fee", fee)

app.listen(5000, () =>{console.log("Listning on port 5000")})