const express = require("express")
const Joi = require("joi")
const cors = require("cors")
const register = require("./routes/register")
const history = require("./routes/track")
const fee = require("./routes/watchPayment")
const auth = require("./routes/auth")
const app = express()
app.use(express.json())
app.use(cors())
app.use("/reg",register)
app.use("/list", history)
app.use("/fee", fee)
app.use("/login", auth)

app.listen(5000, () =>{console.log("Listning on port 5000")})